using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace YoutubeRepoTwo.Views.AdobeDesign
{
    /// <summary>
    /// Interaction logic for get_started.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class get_started : ContentPage
    {
        public get_started()
        {
            InitializeComponent();
        }
    }
}
	